### ISSUE TITLE
non optimal

### ISSUE THREAD

**Issue by rchl** [kapitanluffy/sublime-file-watcher#1]
You are splitting a batch of potentially hundreds of events into separate `run_command` calls which doesn't seem very optimal. Why not just pass all the events as they arrive and let users iterate over them instead?

https://github.com/kapitanluffy/sublime-file-watcher/blob/95c4c06802a0e33fb77760ae26aa519446d72c32/src/file_watcher_handler.py#L49-L50

**Comment by kapitanluffy** [comment]
Thanks @rchl. Updated it. Let me know if that is more optimal

https://github.com/kapitanluffy/sublime-file-watcher/blob/master/src/file_watcher_handler.py#L49-L78

**Comment by rchl** [comment]
Well, you lose information about the original order of events that way, which might be relevant for some use cases. You could just broadcast events as they come.

**Comment by kapitanluffy** [comment]
There you go. I just broadcasted it at once and let the user handle it.

**Comment by rchl** [comment]
That's better.
